ALL_VALID: no

DESCRIPTION_KEYWORDS_I:
- docker
#- kubernetes
- lxc
#- container
#- linux
- windows
- cryptpad
- headscale
- firefox
- obs
- keepassxc
- syncthing
- ubuntu
- qubesos
- debian
- proxmox
- tor

#- privilege escalation
#- escalation
#- privesc
#- high integrity
#- elevated privilege
#- escalation of privilege
#- " sudo "
#- " suid "
#- " pe "
#- " UAC "
#- User Account Control
#- linpeas
#- winpeas
#- docker
#- kubernetes
#- " lxc "
#- podman


DESCRIPTION_KEYWORDS:
- ThisIsACaseSensitiveExample

PRODUCT_KEYWORDS_I:
- docker
- kubernetes
- lxc
- container
- linux
- windows
- cryptpad
- headscale
- firefox
- obs
- keepassxc
- syncthing
- ubuntu
- qubesos
- debian
- proxmox
- tor


PRODUCT_KEYWORDS:
- ThisIsACaseSensitiveExample
